apps/x86/cma34cr_ubuntu/CMakeLists.txt, apps/x86/optiplex9020/CMakeLists.txt, apps/x86/zmq_samples/CMakeLists.txt
Since the applications don't have homogeneous host and guest
architectures, i.e. host is x86_64 and guest is ia32, we update the
CMakeLists.txt of these applications to use the new CMake function to
grab an architectural specific kernel and rootfs image.
Signed-off-by: Damon Lee <Damon.Lee@data61.csiro.au>
=> apps: Update default Linux kernel, rootfs funcs

.github/workflows/test.yml
See also seL4/ci-actions#133 and seL4/ci-actions#132
Currently these are just the builds and the simulation run for ARMVIRT. Hardware runs to be added once the machine queue works again.
=> github: add GH action for VM tests

apps/x86/cma34cr_centos/cma34cr_centos.camkes, apps/x86/minimal/minimal.camkes, apps/x86/optiplex9020/optiplex9020.camkes
Follow-up from comment https://github.com/seL4/seL4/pull/668#issuecomment-980834686
Seems `HAVE_AUTOCONF` is not set anywhere, so this looks like dead code. If this expects somebody else to set this, then this mechanism is broken.
=> remove obsolete HAVE_AUTOCONF

apps/x86/optiplex9020/optiplex9020.camkes
This example doesn't use a multicore configuration.
=> Remove affinity setting from optiplex example

.github/workflows/camkes-vm-deploy.yml
Update to current node16 versions. The old node12 actions are deprecated and will stop working.
=> github: bump GitHub action versions

README.md, apps/Arm/vm_minimal/CMakeLists.txt, apps/Arm/vm_minimal/settings.cmake, apps/Arm/vm_minimal/zcu102/devices.camkes
Test with: https://github.com/seL4/camkes-vm/pull/112
Test with: https://github.com/seL4/camkes-vm-images/pull/6
=> vm_minimal: add zcu102 support

apps/Arm/vm_minimal/CMakeLists.txt
Simplify command and avoids depending on shell features, just use program features.
=> CMake: avoid using bash and output redirection

.github/workflows/camkes-vm-deploy.yml
Forks usually don't have a valid token, so CI fail then.
We are doing this check in other repos also, so it seems good enough the fix the annoying warning on my fork evertime a rebase master. There are smarter ways to handle this, as forks could also have tokens - but that can be done when we have a fork that really does this.
=> CI: don't run hardware test on forks

README.md
- x64 was still marked as "coming"
- clarify arm vs x86 build instructions
- update capDL image name (no longer experimental)
- fix typos and markdown warnings
Should fix #52
=> README: bring build instructions up to date

apps/Arm/vm_introspect/src/cross_vm_connection.c, apps/Arm/vm_introspect/src/init_dataport_ram.c
The changes from sel4/camkes-vm#48 and sel4/camkes-vm#62 have broken `vm_introspect`. This has not been noticed, because there is no CI coverage for it yet (https://github.com/seL4/camkes-vm-examples/issues/38). With this patch the build work locally for me again.
=> vm_introspect: fix build breaker and warning

.github/workflows/test-hw.yml
Allows hardware build and test via labels `hw-build` and `hw-test` for this repo also. So we don't have to ab-use https://github.com/seL4/camkes-vm for hardware test when the actual change and PR is in the examples here. This basically copies things from `camkes-vm-deploy.yml` (but with `fail-fast: true`) and adapts the label logic from kernel repos.
It seems to work, see testing from https://github.com/seL4/camkes-vm-examples/pull/59
Could be optimized that the hardware builds don't build `vm_minimal_sim` on ARMv8, seems the `sim: true` from `ci-actions/camkes-vm/builds.yml` is ignored.
This needs https://github.com/seL4/ci-actions/pull/316, otherwise some runs fail because the setting are ignored.
=> CI: support hardware build and test for PRs

.github/workflows/test-hw.yml
This should have been in https://github.com/seL4/camkes-vm-examples/pull/60 already.
=> CI: use commits from PR and not from master

.github/workflows/test-hw.yml
Just cancel all older hardware runs for the current PR.
This fixes https://github.com/seL4/camkes-vm-examples/issues/65
=> CI: don't have PR runs cancel each other

.github/workflows/camkes-vm-deploy.yml
"Camkes VM" is also used in `.github/workflows/test.yml`. On the workflow status page it is a bit odd of there are two workflows with the name name.
=> CI: pick unique name for deployment workflow

apps/Arm/vm_virtio_net/CMakeLists.txt, apps/Arm/vm_virtio_net/overlay_files/init_scripts/zynqmp/arping_test, apps/Arm/vm_virtio_net/overlay_files/init_scripts/zynqmp/ping_test, apps/Arm/vm_virtio_net/settings.cmake, apps/Arm/vm_virtio_net/zcu102/2022_1/devices.camkes
(Edit: testing with merged PRs)
=> vm_virtio_net: add zcu102 support

apps/Arm/vm_minimal/zcu102/2022_1/devices.camkes
See also https://github.com/seL4/camkes-vm-images/pull/8, https://github.com/seL4/camkes-vm/pull/129
=> vm_minimal, zcu102: add petalinux 2022.1 support

apps/Arm/vm_minimal/zcu102/2021_1/devices.camkes
This commit removes extra devices that are not needed for a minimal boot image. It also adds a comment explaining why the passthrough and emulated devices must be listed under the plat_keep_devices node.
=> vm_minimal, zcu102: update plat_keep_devices

apps/Arm/vm_minimal/CMakeLists.txt
The QEMU/aarch32 platform is not supported actively at the moment for virtualization.
See also https://github.com/seL4/camkes-vm-examples/issues/73
=> vm_minimal, QEMU: block aarch32 build

.github/workflows/camkes-vm-deploy.yml
Python 3.12 in Ubuntu 24.04 has incompatible packages.
=> github: pin Ubuntu 22.04 for deployment step

apps/x86/zmq_samples/README.md
The GettingStarted page was renamed and in this case was the wrong target anyway.
=> zmq_samples/README: fix link
